name: goreleaser

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '*'

jobs:
  goreleaser:
    strategy:
        matrix:
          golang: [1.18]
          ubuntu_os: [1804]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.18

      - name: Prepare
        id: prepare
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo ::set-output name=tag_name::${TAG}
  release:
    runs-on: ubuntu-latest
    needs:
      - goreleaser
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.18

      - name: Prepare
        id: prepare
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo ::set-output name=tag_name::${TAG}
      - name: Release
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          make build-release
